version: '3.7'
services:
  geoserver:
    image: sogis/geoserver:2.20.1
    #environment:
    ports:
      - 8080:8080
    volumes:
      - ~/tmp/geoserver/data:/usr/local/geoserver/data:delegated
    depends_on:
      - db
  db:
    image: sogis/oereb-db:2
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: pub
      POSTGRES_PASSWORD: mysecretpassword
      PG_READ_PWD: dmluser
      PG_WRITE_PWD: ddluser
      GRETL_PG_WRITE_PWD: gretl
    ports:
      - 54322:5432
    volumes:
    - ~/tmp/pgdata:/var/lib/postgresql/data:delegated
